name: Train ML Model (MLflow)

on:
  push:
    branches:
      - main
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting MLflow training workflow..."

      - name: Run actions/checkout@v4
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set MLflow Tracking URI
        run: |
          export MLFLOW_TRACKING_URI=./mlruns
          echo "MLflow Tracking URI set to ./mlruns"

      - name: Run mlflow project
        run: |
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(ls -t mlruns/0 | head -1)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run ID is $RUN_ID"

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/

      - name: Install MLflow Docker extras
        run: |
          pip install mlflow[extras]

      - name: Build Docker Image from MLflow Model
        run: |
          mlflow models build-docker \
            -m mlruns/1/${{ steps.get_run.outputs.run_id }} \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ steps.get_run.outputs.run_id }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ steps.get_run.outputs.run_id }}

      - name: Complete job
        run: echo "Job completed successfully!"
