name: Train ML Model (MLflow)

on:
  push:
    branches:
      - main
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: 3.10
          channels: conda-forge
          activate-environment: ""

      - name: Show Conda Info
        run: |
          conda --version
          conda env list

      - name: Run MLflow project (create conda env)
        run: mlflow run .

      - name: Get latest MLflow run_id
        run: |
          echo "LATEST RUN:"
          ls -t mlruns/0 | head -1
