name: Train ML Model (MLflow)

on:
  push:
    branches:
      - main
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Environment
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup MLflow tracking
        run: |
          mkdir -p $GITHUB_WORKSPACE/mlruns
          echo "MLFLOW_TRACKING_URI=$GITHUB_WORKSPACE/mlruns" >> $GITHUB_ENV
        shell: bash

      - name: Create MLflow experiment
        run: |
          python - <<EOF
          import mlflow
          mlflow.set_tracking_uri("$GITHUB_WORKSPACE/mlruns")
          mlflow.set_experiment("Default")  # otomatis bikin folder mlruns/0
          EOF
        shell: bash

      - name: Run MLflow project
        run: mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(ls -t $GITHUB_WORKSPACE/mlruns/0 | grep -E '^[a-f0-9]{32}$' | head -1)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run ID is $RUN_ID"

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: $GITHUB_WORKSPACE/mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/

      - name: Install MLflow Docker extras
        run: pip install mlflow[extras]

      - name: Get latest model version
        id: get_model
        run: |
          MODEL_ID=$(ls -t $GITHUB_WORKSPACE/mlruns/0/models | grep -E '^m-[a-f0-9]{32}$' | head -1)
          echo "model_id=$MODEL_ID" >> $GITHUB_OUTPUT
          echo "Latest model ID is $MODEL_ID"

      - name: Build Docker image from MLflow model
        run: |
          mlflow models build-docker \
            -m $GITHUB_WORKSPACE/mlruns/0/models/${{ steps.get_model.outputs.model_id }}/artifacts \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ steps.get_run.outputs.run_id }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ steps.get_run.outputs.run_id }}

      - name: Complete job
        run: echo "Job completed successfully!"
