name: Train ML Model (MLflow)

on:
  push:
    paths:
      - "**.py"
      - "MLproject"
      - "conda.yaml"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          channels: conda-forge
          channel-priority: strict
          activate-environment: ""

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MLflow project
        run: |
          mlflow run .
