name: Train ML Model (MLflow)

on:
  push:
    branches:
      - main
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install "mlflow[extras]"

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=./mlruns" >> $GITHUB_ENV

      - name: Run mlflow project
        run: mlflow run . --env-manager=local

      - name: Get latest MLflow run ID
        id: get_run
        run: |
          RUN_ID=$(ls -t mlruns/0 | head -1)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run ID: $RUN_ID"

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/

      # =============================================================
      # BUILD DOCKER IMAGE DARI MODEL MLFLOW
      # =============================================================

      - name: Generate Dockerfile using MLflow
        run: |
          mlflow models prepare-docker \
            -m mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/model \
            --output-dir mlflow_docker

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ steps.get_run.outputs.run_id }} mlflow_docker

      # =============================================================
      # LOGIN & PUSH KE DOCKER HUB
      # =============================================================

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:${{ steps.get_run.outputs.run_id }}

      - name: Complete job
        run: echo "Job completed successfully!"
