name: Train ML Model (MLflow)

on:
  push:
    branches:
      - main
      - master

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: stroke-env
          environment-file: conda.yaml
          python-version: 3.10

      - name: Verify conda + python
        shell: bash -l {0}
        run: |
          conda info
          which python
          python --version

      - name: Install dependencies (if needed)
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt

      - name: Run MLflow project using conda
        shell: bash -l {0}
        run: |
          mlflow run . --env-manager=conda

      - name: Show latest MLflow run
        shell: bash -l {0}
        run: |
          echo "LATEST RUN:"
          ls -t mlruns/0 | head -1
