name: Train ML Model (MLflow)

on:
  push:
    paths:
      - "**.py"
      - "MLproject"
      - "conda.yaml"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          channels: conda-forge
          auto-update-conda: false
          channel-priority: strict
          python-version: "3.10"

      - name: Initialize conda
        shell: bash -l {0}
        run: |
          conda init bash
          source ~/.bashrc

      - name: Install deps for MLproject
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt

      - name: Run MLflow project
        shell: bash -l {0}
        run: |
          mlflow run .
