name: Train ML Model (MLflow)

on:
  workflow_dispatch: # manual trigger
  push:
    paths:
      - "**.py"
      - "MLproject"
      - "conda.yaml"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda.yaml
          activate-environment: mlflow-env

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MLflow project
        run: |
          mlflow run .
